apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-instance
  namespace: grafana-operator
spec:
  config:
    log:
      mode: console
    security:
      admin_password: admin
      admin_user: admin
    smtp:
      enabled: 'true'
      from_address: grafana-aro-noreply@example.com
      host: 'mailhost.example.com:587'
      skip_verify: 'true'
  version: >-
    docker.io/grafana/grafana@sha256:a0f881232a6fb71a0554a47d0fe2203b6888fe77f4cefb7ea62bed7eb54e13c3