apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-serviceaccount
  namespace: grafana-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-monitoring-reader
rules:
- apiGroups: [""]
  resources: ["nodes", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors", "prometheusrules"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-monitoring-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-monitoring-reader
subjects:
- kind: ServiceAccount
  name: grafana-serviceaccount
  namespace: grafana-operator
---
# Role for accessing Loki in openshift-logging namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: openshift-logging
  name: loki-reader
rules:
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["loki.grafana.com"]
  resources: ["lokistacks"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-loki-reader
  namespace: openshift-logging
subjects:
- kind: ServiceAccount
  name: grafana-serviceaccount
  namespace: grafana-operator
roleRef:
  kind: Role
  name: loki-reader
  apiGroup: rbac.authorization.k8s.io
