apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-managed
    # directory:
    #   include: "argocd-rbac.yaml"
    repoURL: https://github.com/adhambbaker/github-arc-gitops
    targetRevision: main

  syncPolicy:
    automated:
      prune: false
      selfHeal: false