apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-arc-controller
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set-controller
    targetRevision: "0.12.1"
    helm:
      parameters:
      - name: podAnnotations."prometheus\.io/scrape"
        value: "true"
      - name: podAnnotations."prometheus\.io/path"
        value: "/metrics"
      - name: podAnnotations."prometheus\.io/port"
        value: "8080"
      releaseName: arc
      values: |
        metrics:
          controllerManagerAddr: ":8080"
          listenerAddr: ":8080"
          listenerEndpoint: "/metrics"
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true