# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: github-arc-runners
#   namespace: openshift-gitops
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: ghcr.io/actions/actions-runner-controller-charts
#     chart: gha-runner-scale-set
#     targetRevision: "0.12.1"
#     helm:
#       releaseName: arc-runner-set
#       values: |
#       runnerScaleSetName: arc-runner-set
#       githubConfigUrl: https://github.com/adhambbaker
#       githubConfigSecret:
#         github_token: xx
#       controllerServiceAccount:
#         namespace: arc-system
#         name: arc-gha-rs-controller
      
#       minRunners: 1
#       maxRunners: 3
      
#       template:
#         spec:
#           containers:
#             - name: runner
#               image: ghcr.io/actions/actions-runner:latest
#               command: ["/home/runner/run.sh"]
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: arc-runners
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true