apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-arc-runners
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set
    targetRevision: "0.9.3"
    helm:
      values: |
        runnerScaleSetName: arc-runner-set
        githubConfigUrl: https://github.com/adhambbaker
        githubConfigSecret: github-token
        
        minRunners: 0
        maxRunners: 3
        
        # OpenShift compatibility
        template:
          spec:
            securityContext:
              runAsNonRoot: true
              fsGroup: 1001
            containers:
            - name: runner
              securityContext:
                runAsUser: 1001
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: false
                capabilities:
                  drop:
                  - ALL
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true