apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-arc-controller-gitops
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
  sources:
  - repoURL: https://github.com/adhambbaker/github-arc
    # chart: gha-runner-scale-set-controller
    # targetRevision: "0.12.1"
    targetRevision: develop
    path: charts/github-arc-controller/gha-runner-scale-set-controller
    helm:
      releaseName: arc
      valueFiles:
      - $values/deployments/arc-controller/values.yaml
  - repoURL: https://github.com/adhambbaker/github-arc
    targetRevision: develop
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true