apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: github-arc-controller-envs
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - env: dev
        namespace: arc-system-dev
        valuesFile: github-arc-controller-dev-values.yaml
        syncPolicy: false  # Manual sync for dev
        replicaCount: "1"
      # - env: staging
      #   namespace: arc-system-staging
      #   valuesFile: github-arc-controller-staging-values.yaml
      #   syncPolicy: "true"   # Auto sync for staging
      #   replicaCount: "1"
      # - env: prod
      #   namespace: arc-system-prod
      #   valuesFile: github-arc-controller-prod-values.yaml
      #   syncPolicy: "false"  # Manual sync for production (safety)
      #   replicaCount: "2"
  template:
    metadata:
      name: 'github-arc-controller-{{env}}'
      namespace: openshift-gitops
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      labels:
        environment: '{{env}}'
        component: github-arc-controller
    spec:
      project: default
      ignoreDifferences:
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          jsonPointers:
            - /spec/preserveUnknownFields
      sources:
      - repoURL: ghcr.io/actions/actions-runner-controller-charts
        chart: gha-runner-scale-set-controller
        targetRevision: "0.12.1"
        helm:
          releaseName: 'arc-controller-{{env}}'
          valueFiles:
          - '$values/values/{{valuesFile}}'
      - repoURL: https://github.com/adhambbaker/github-arc-gitops.git
        targetRevision: main
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      # syncPolicy:
      #   automated:
      #     prune: "{{syncPolicy}}"
      #     selfHeal: "{{syncPolicy}}"
        # syncOptions:
        #   - CreateNamespace=true
        #   - ServerSideApply=true
        #   - RespectIgnoreDifferences=true
