apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-arc-controller
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  ignoreDifferences:
    - group: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: ephemeralrunnersets.actions.github.com
      jsonPointers:
        - /status
    - group: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: ephemeralrunners.actions.github.com
      jsonPointers:
        - /status
    - group: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: autoscalingrunnersets.actions.github.com
      jsonPointers:
        - /status
    - group: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: autoscalinglisteners.actions.github.com
      jsonPointers:
        - /preserveUnknownFields
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set-controller
    targetRevision: "0.12.1"
    helm:
      releaseName: arc
      values: |
        # Minimal configuration for OpenShift compatibility
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true