apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-arc-controller
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set-controller
    targetRevision: 0.9.3
    helm:
      releaseName: arc-controller
      values: |
        runnerScaleSetName: "arc-runner-set"
        
        githubConfigUrl: "https://github.com/adhambbaker"
        githubConfigSecret: "github-token"
        
        # Basic runner configuration
        minRunners: 0
        maxRunners: 5
        
        # Container mode for Kubernetes jobs
        containerMode:
          type: "kubernetes"
        
        # Resource limits
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "100m"
            memory: "256Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true