apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: "8.5.2"
    helm:
      releaseName: grafana
      values: |
        # Basic admin credentials
        adminUser: admin
        adminPassword: admin123
        
        # Completely disable persistence for now to avoid permission issues
        persistence:
          enabled: false
        
        # Service
        service:
          type: ClusterIP
          port: 80
        
        # Disable ingress
        ingress:
          enabled: false
        
        # Minimal resources
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        
        # Completely empty security contexts - let OpenShift handle everything
        securityContext: null
        containerSecurityContext: null
        podSecurityContext: null
        
        # Disable ALL init containers
        initChownData:
          enabled: false
        
        # Disable download dashboards completely
        downloadDashboards:
          enabled: false
        downloadDashboardsImage:
          enabled: false
        
        # Disable all sidecars
        sidecar:
          dashboards:
            enabled: false
          datasources:
            enabled: false
          image:
            tag: ""
        
        # Disable test framework
        testFramework:
          enabled: false
        
        # Use minimal image
        image:
          repository: grafana/grafana
          tag: "10.4.0"  # Use older, more stable version
          pullPolicy: IfNotPresent
        
        # Basic service account without annotations
        serviceAccount:
          create: true
          name: grafana
          annotations: {}
        
        # Disable RBAC
        rbac:
          create: false
          pspEnabled: false
        
        # Override default pod annotations to remove seccomp
        podAnnotations: {}
        
        # Disable all extra features
        plugins: []
        notifiers: {}
        alerting: {}
        
        # Simple grafana.ini without security overrides
        grafana.ini:
          server:
            root_url: "/"
          users:
            allow_sign_up: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true