apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: "8.5.2"
    helm:
      releaseName: grafana
      values: |
        # Basic admin credentials
        adminUser: admin
        adminPassword: admin123
        
        # Minimal persistence
        persistence:
          enabled: true
          size: 5Gi
          accessModes:
            - ReadWriteOnce
        
        # Service
        service:
          type: ClusterIP
          port: 80
        
        # Disable ingress
        ingress:
          enabled: false
        
        # Minimal resources
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        
        # Let OpenShift handle security context automatically
        securityContext: {}
        containerSecurityContext: {}
        
        # Disable all init containers and sidecars
        initChownData:
          enabled: false
        
        sidecar:
          dashboards:
            enabled: false
          datasources:
            enabled: false
        
        # Disable test framework
        testFramework:
          enabled: false
        
        # Disable download dashboards
        downloadDashboards:
          enabled: false
        
        # Basic service account
        serviceAccount:
          create: true
          name: grafana
        
        # Disable RBAC to avoid conflicts
        rbac:
          create: false
          pspEnabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
