apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-logging-stack
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/adhambbaker/github-arc-gitops.git
    targetRevision: main
    path: monitoring/openshift-logging
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
