# apiVersion: loki.grafana.com/v1
# kind: LokiStack
# metadata:
#   name: logging-loki
#   namespace: openshift-logging
# spec:
#   size: 1x.small
#   storage:
#     schemas:
#     - version: v12
#       effectiveDate: "2022-06-01"
#     secret:
#       name: logging-loki-s3
#       type: s3
#   storageClassName: gp3-csi
#   tenants:
#     mode: openshift-logging

apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  annotations:
  name: logging-loki
  namespace: openshift-logging
spec:
  managementState: Managed
  size: 1x.demo
  storage:
    schemas:
      - effectiveDate: '2024-04-02'
        version: v13
    secret:
      name: logging-loki-s3
      type: s3
  storageClassName: crc-csi-hostpath-provisioner
  tenants:
    mode: openshift-logging







# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: logging-loki-s3
#   namespace: openshift-logging
# type: Opaque
# stringData:
#   # For development/testing - using local storage
#   # In production, replace with actual S3 credentials
#   bucketname: "loki-chunks"
#   endpoint: "http://minio.openshift-logging.svc.cluster.local:9000"
#   access_key_id: "loki"
#   access_key_secret: "supersecret"
#   region: "us-east-1"
# ---
# # MinIO for local S3 storage (development only)
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: minio
#   namespace: openshift-logging
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: minio
#   template:
#     metadata:
#       labels:
#         app: minio
#     spec:
#       containers:
#       - name: minio
#         image: quay.io/minio/minio:latest
#         args:
#         - server
#         - /data
#         - --console-address
#         - ":9001"
#         env:
#         - name: MINIO_ACCESS_KEY
#           value: "loki"
#         - name: MINIO_SECRET_KEY
#           value: "supersecret"
#         ports:
#         - containerPort: 9000
#         - containerPort: 9001
#         volumeMounts:
#         - name: data
#           mountPath: /data
#         resources:
#           requests:
#             cpu: 100m
#             memory: 128Mi
#           limits:
#             cpu: 500m
#             memory: 512Mi
#       volumes:
#       - name: data
#         emptyDir: {}
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: minio
#   namespace: openshift-logging
# spec:
#   selector:
#     app: minio
#   ports:
#   - name: api
#     port: 9000
#     targetPort: 9000
#   - name: console
#     port: 9001
#     targetPort: 9001
