apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki-datasource
  namespace: grafana-operator
spec:
  allowCrossNamespaceImport: false
  datasource:
    access: proxy
    isDefault: false
    jsonData:
      maxLines: 1000
      timeInterval: 30s
      tlsSkipVerify: true
    name: loki
    secureJsonData:
      httpHeaderValue1: 'Bearer '
    type: loki
    url: 'http://logging-loki-gateway-http.openshift-logging.svc:8080'
  instanceSelector:
    matchLabels:
      dashboards: grafana-logging
  plugins:
    - name: grafana-clock-panel
      version: 1.3.0
  resyncPeriod: 10m0s
# ---
# apiVersion: grafana.integreatly.org/v1beta1
# kind: GrafanaDataSource
# metadata:
#   name: prometheus-datasource
#   namespace: grafana-operator
# spec:
#   instanceSelector:
#     matchLabels:
#       dashboards: "grafana-logging"
#   datasource:
#     name: Prometheus
#     type: prometheus
#     access: proxy
#     url: https://thanos-querier.openshift-monitoring.svc:9091
#     isDefault: true
#     jsonData:
#       tlsSkipVerify: true
#       timeInterval: "30s"
#       httpMethod: "GET"
#     secureJsonData:
#       httpHeaderValue1: "Bearer "
# ---
# apiVersion: grafana.integreatly.org/v1beta1
# kind: GrafanaDataSource
# metadata:
#   name: prometheus-user-workload
#   namespace: grafana-operator
# spec:
#   instanceSelector:
#     matchLabels:
#       dashboards: "grafana-logging"
#   datasource:
#     name: Prometheus-UserWorkload
#     type: prometheus
#     access: proxy
#     url: https://thanos-querier.openshift-user-workload-monitoring.svc:9091
#     isDefault: false
#     jsonData:
#       tlsSkipVerify: true
#       timeInterval: "30s"
#       httpMethod: "GET"
#     secureJsonData:
#       httpHeaderValue1: "Bearer "
