apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio

resources:
- base/minio-deploy.yaml
- base/minio-pvc.yaml
- base/minio-svc.yaml
- base/minio-route.yaml

generators:
- ./gen/secret-generator.yaml