apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio-app
    app.kubernetes.io/component: minio-s3
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: S3_SUBSYSTEM
    app.openshift.io/runtime: S3
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |
          mkdir -p /data/thanos && \
          mkdir -p /data/loki
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 20m
            memory: 100Mi
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        terminationMessagePath: /dev/termination-log
        env:
          - name: MINIO_ROOT_USER
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: minio_root_user
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: minio_root_password
        # - name: MINIO_ACCESS_KEY
        #   value: minio
        # - name: MINIO_SECRET_KEY
        #   value: xxx
        image: minio/minio
        args:
          - server
          - /data
          - --console-address
          - :9090
        name: minio
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        ports:
        - containerPort: 9000
        imagePullPolicy: IfNotPresent
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio-pvc
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 6