# OpenShift GitOps ArgoCD RBAC Configuration
# Converted from Terraform to YAML for GitOps management

# Role for arc-system namespace operations
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-gitops-arc-system-role
  namespace: arc-system
rules:
# Core resources needed for GitHub ARC
- apiGroups: [""]
  resources: ["serviceaccounts", "secrets", "configmaps", "services", "endpoints", "pods"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# Apps resources for deployments
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# RBAC resources
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# GitHub ARC custom resources
- apiGroups: ["actions.github.com"]
  resources: ["*"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# Monitoring
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
# RoleBinding for arc-system namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-gitops-arc-system-rolebinding
  namespace: arc-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-gitops-arc-system-role
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
---
# Role for arc-runners namespace operations
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-gitops-arc-runners-role
  namespace: arc-runners
rules:
# Core resources needed for GitHub ARC runners
- apiGroups: [""]
  resources: ["serviceaccounts", "secrets", "configmaps", "services", "endpoints", "pods", "persistentvolumeclaims"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# Apps resources for deployments
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# RBAC resources
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# GitHub ARC custom resources
- apiGroups: ["actions.github.com"]
  resources: ["*"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# Autoscaling
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
# RoleBinding for arc-runners namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-gitops-arc-runners-rolebinding
  namespace: arc-runners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-gitops-arc-runners-role
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
---
# Role for monitoring namespace operations
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-gitops-monitoring-role
  namespace: monitoring
rules:
# Core resources needed for Grafana
- apiGroups: [""]
  resources: ["serviceaccounts", "secrets", "configmaps", "services", "endpoints", "pods", "persistentvolumeclaims"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# Apps resources for deployments
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# RBAC resources
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# Monitoring resources
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors", "prometheusrules"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# OpenShift routes
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
# RoleBinding for monitoring namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-gitops-monitoring-rolebinding
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-gitops-monitoring-role
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
---
# ClusterRole for ArgoCD with extended permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-cluster-role
rules:
# Custom Resource Definitions management (including GitHub ARC CRDs)
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  resourceNames: [
    "autoscalinglisteners.actions.github.com",
    "autoscalingrunnersets.actions.github.com", 
    "ephemeralrunners.actions.github.com",
    "ephemeralrunnersets.actions.github.com"
  ]
  verbs: ["*"]
# Admission controllers management
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# Core resources management
- apiGroups: [""]
  resources: ["namespaces", "serviceaccounts"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# Applications and deployments
- apiGroups: ["apps", "extensions"]
  resources: ["deployments", "replicasets"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# Core resources (pods, services, etc.)
- apiGroups: ["", "apps", "extensions"]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# Monitoring resources
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# GitHub ARC specific resources
- apiGroups: ["actions.github.com"]
  resources: ["*"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["actions.summerwind.dev"]
  resources: ["*"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# OpenShift specific resources
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete", "use"]
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# RBAC resources (for managing service accounts and permissions)
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# Storage resources
- apiGroups: [""]
  resources: ["persistentvolumes", "persistentvolumeclaims"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# Networking resources
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies", "ingresses"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
# ClusterRoleBinding for ArgoCD
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-cluster-role
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
